# Generated by Django 2.1.5 on 2019-01-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_auto_20190110_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='n_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_pingbacks',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
    ]
