# Generated by Django 2.2.1 on 2019-05-03 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('query', '0005_blog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='name',
        ),
        migrations.AddField(
            model_name='author',
            name='blogs',
            field=models.ManyToManyField(to='query.Blog'),
        ),
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='author',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='ThemeBlog',
        ),
    ]
